import type { TunerField } from "@/lib/coverly/tuner";
import type { DockConfig } from "@/lib/coverly/dock-config";
import type { FlyConfig } from "@/lib/coverly/fly-config";

export const DOCK_TITLE = "Similar covers · dock";

export const DOCK_FIELDS: TunerField<DockConfig>[] = [
  {
    key: "peak",
    label: "Peak scale",
    hint: "size of the cover under the cursor",
    min: 1,
    max: 2.2,
    step: 0.01,
    unit: "×",
  },
  {
    key: "reach",
    label: "Reach",
    hint: "falloff distance, as a multiple of cover width",
    min: 0.1,
    max: 3,
    step: 0.05,
    unit: "w",
  },
  {
    key: "curve",
    label: "Curve",
    hint: "higher drops off faster past the edge",
    min: 1,
    max: 6,
    step: 0.1,
  },
  {
    key: "ease",
    label: "Settle",
    hint: "how long a cover takes to reach its size",
    min: 0,
    max: 600,
    step: 10,
    unit: "ms",
  },
  {
    key: "anchor",
    label: "Growth anchor",
    hint: "1 grows straight up, 0 grows straight down",
    min: 0,
    max: 1,
    step: 0.05,
  },
  {
    key: "tilt",
    label: "Tilt",
    hint: "rotation of the cover under the cursor",
    min: -12,
    max: 12,
    step: 0.5,
    unit: "°",
  },
  {
    key: "height",
    label: "Cover height",
    hint: "resting height of each cover",
    min: 56,
    max: 180,
    step: 2,
    unit: "px",
  },
  {
    key: "gap",
    label: "Gap",
    hint: "space between covers",
    min: 0,
    max: 32,
    step: 1,
    unit: "px",
  },
  {
    key: "volume",
    label: "Tick volume",
    hint: "loudness of the hover sound",
    min: 0,
    max: 1,
    step: 0.05,
  },
];

export const FLY_TITLE = "Save to board · flight";

export const FLY_FIELDS: TunerField<FlyConfig>[] = [
  {
    key: "duration",
    label: "Flight time",
    hint: "how long the cover takes to reach the board",
    min: 200,
    max: 1800,
    step: 20,
    unit: "ms",
  },
  {
    key: "lift",
    label: "Arc height",
    hint: "how high the cover rises mid-flight",
    min: 0,
    max: 400,
    step: 10,
    unit: "px",
  },
  {
    key: "arcX",
    label: "Arc bias X",
    hint: "where along the path the arc peaks, horizontally",
    min: 0,
    max: 1,
    step: 0.05,
  },
  {
    key: "arcY",
    label: "Arc bias Y",
    hint: "where along the path the arc peaks, vertically",
    min: 0,
    max: 1,
    step: 0.05,
  },
  {
    key: "spin",
    label: "Spin",
    hint: "total rotation over the flight",
    min: 0,
    max: 720,
    step: 10,
    unit: "°",
  },
  {
    key: "pop",
    label: "Launch pop",
    hint: "scale spike as the cover lifts off",
    min: 1,
    max: 2,
    step: 0.02,
    unit: "×",
  },
  {
    key: "endScale",
    label: "Landing size",
    hint: "size as it drops into the board",
    min: 0.02,
    max: 0.6,
    step: 0.02,
    unit: "×",
  },
  {
    key: "endOpacity",
    label: "Landing fade",
    hint: "opacity as it lands",
    min: 0,
    max: 1,
    step: 0.05,
  },
  {
    key: "bounce",
    label: "Board bounce",
    hint: "how much the board icon kicks on arrival",
    min: 1,
    max: 1.6,
    step: 0.02,
    unit: "×",
  },
  {
    key: "bounceMs",
    label: "Bounce time",
    hint: "how long the board icon kick lasts",
    min: 0,
    max: 900,
    step: 20,
    unit: "ms",
  },
  {
    key: "turn",
    label: "Launch sound",
    hint: "loudness of the page turn as the cover lifts off",
    min: 0,
    max: 1,
    step: 0.05,
  },
  {
    key: "swish",
    label: "Landing sound",
    hint: "loudness of the swish as the cover lands",
    min: 0,
    max: 1,
    step: 0.05,
  },
];
