export type Work = {
  n: number;
  vol: 1 | 2;
  kind: "poster" | "pattern" | "mockup" | "motion";
  title: string;
  src: string;
  poster?: string;
  w: number;
  h: number;
};

export const WORKS: Work[] = [
  {
    n: 1,
    vol: 1,
    kind: "poster",
    title: "Low-Res God",
    src: "/studio/NM-0001_poster_low-res-god.jpg",
    w: 960,
    h: 1200,
  },
  {
    n: 2,
    vol: 1,
    kind: "poster",
    title: "Whorl",
    src: "/studio/NM-0002_poster_whorl.jpg",
    w: 960,
    h: 1200,
  },
  {
    n: 3,
    vol: 1,
    kind: "poster",
    title: "Cipher",
    src: "/studio/NM-0003_poster_cipher.jpg",
    w: 960,
    h: 1200,
  },
  {
    n: 4,
    vol: 1,
    kind: "poster",
    title: "Sear",
    src: "/studio/NM-0004_poster_sear.jpg",
    w: 960,
    h: 1200,
  },
  {
    n: 5,
    vol: 1,
    kind: "poster",
    title: "Cut-Up / Misreg",
    src: "/studio/NM-0005_poster_cut-up-misreg.jpg",
    w: 960,
    h: 1200,
  },
  {
    n: 6,
    vol: 1,
    kind: "poster",
    title: "Dahlia",
    src: "/studio/NM-0006_poster_dahlia.jpg",
    w: 960,
    h: 1200,
  },
  {
    n: 7,
    vol: 1,
    kind: "poster",
    title: "Fold",
    src: "/studio/NM-0007_poster_fold.jpg",
    w: 960,
    h: 1200,
  },
  {
    n: 8,
    vol: 1,
    kind: "poster",
    title: "Terrain Survey 081",
    src: "/studio/NM-0008_poster_terrain-survey.jpg",
    w: 960,
    h: 1200,
  },
  {
    n: 9,
    vol: 1,
    kind: "poster",
    title: "Hiss",
    src: "/studio/NM-0009_poster_hiss.jpg",
    w: 960,
    h: 1200,
  },
  {
    n: 10,
    vol: 1,
    kind: "poster",
    title: "Stipple",
    src: "/studio/NM-0010_poster_stipple.jpg",
    w: 960,
    h: 1200,
  },
  {
    n: 12,
    vol: 1,
    kind: "pattern",
    title: "Zig",
    src: "/studio/NM-0012_pattern_zig.jpg",
    w: 1200,
    h: 1200,
  },
  {
    n: 13,
    vol: 1,
    kind: "pattern",
    title: "Weave",
    src: "/studio/NM-0013_pattern_weave.jpg",
    w: 1200,
    h: 1200,
  },
  {
    n: 14,
    vol: 1,
    kind: "pattern",
    title: "Counterchange",
    src: "/studio/NM-0014_pattern_counterchange.jpg",
    w: 1200,
    h: 1200,
  },
  {
    n: 15,
    vol: 1,
    kind: "pattern",
    title: "Ten Print",
    src: "/studio/NM-0015_pattern_ten-print.jpg",
    w: 1200,
    h: 1200,
  },
  {
    n: 16,
    vol: 1,
    kind: "pattern",
    title: "Dither Swatch",
    src: "/studio/NM-0016_pattern_dither-swatch.jpg",
    w: 1200,
    h: 1200,
  },
  {
    n: 17,
    vol: 1,
    kind: "mockup",
    title: "Fly-Poster Wall",
    src: "/studio/NM-0017_mockup_fly-poster-wall.jpg",
    w: 1800,
    h: 1125,
  },
  {
    n: 22,
    vol: 1,
    kind: "mockup",
    title: "Signal & Noise Zine",
    src: "/studio/NM-0022_mockup_zine-spread.jpg",
    w: 1800,
    h: 1238,
  },
  {
    n: 23,
    vol: 1,
    kind: "motion",
    title: "Whorl · Loop",
    src: "/studio/NM-0023_motion_whorl-loop.mp4",
    poster: "/studio/NM-0023_motion_whorl-loop_poster.jpg",
    w: 1080,
    h: 1350,
  },
  {
    n: 24,
    vol: 1,
    kind: "motion",
    title: "Dahlia · Loop",
    src: "/studio/NM-0024_motion_dahlia-loop.mp4",
    poster: "/studio/NM-0024_motion_dahlia-loop_poster.jpg",
    w: 1080,
    h: 1350,
  },
  {
    n: 25,
    vol: 1,
    kind: "motion",
    title: "Dither Tide",
    src: "/studio/NM-0025_motion_dither-tide.mp4",
    poster: "/studio/NM-0025_motion_dither-tide_poster.jpg",
    w: 1080,
    h: 1350,
  },
  {
    n: 26,
    vol: 1,
    kind: "motion",
    title: "Fold · Reroll",
    src: "/studio/NM-0026_motion_fold-reroll.mp4",
    poster: "/studio/NM-0026_motion_fold-reroll_poster.jpg",
    w: 1080,
    h: 1350,
  },
  {
    n: 27,
    vol: 2,
    kind: "poster",
    title: "Altitude",
    src: "/studio/NM-0027_poster_v2-altitude.jpg",
    w: 960,
    h: 1200,
  },
  {
    n: 28,
    vol: 2,
    kind: "poster",
    title: "Tarn",
    src: "/studio/NM-0028_poster_v2-tarn.jpg",
    w: 960,
    h: 1200,
  },
  {
    n: 29,
    vol: 2,
    kind: "poster",
    title: "Headland",
    src: "/studio/NM-0029_poster_v2-headland.jpg",
    w: 960,
    h: 1200,
  },
  {
    n: 30,
    vol: 2,
    kind: "poster",
    title: "Treeline",
    src: "/studio/NM-0030_poster_v2-treeline.jpg",
    w: 960,
    h: 1200,
  },
  {
    n: 31,
    vol: 2,
    kind: "poster",
    title: "Massif",
    src: "/studio/NM-0031_poster_v2-massif.jpg",
    w: 960,
    h: 1200,
  },
  {
    n: 32,
    vol: 2,
    kind: "poster",
    title: "Estuary",
    src: "/studio/NM-0032_poster_v2-estuary.jpg",
    w: 960,
    h: 1200,
  },
  {
    n: 33,
    vol: 2,
    kind: "mockup",
    title: "Altitude · Plywood Wall",
    src: "/studio/NM-0033_mockup_v2-plywood-altitude.jpg",
    w: 1800,
    h: 1013,
  },
  {
    n: 34,
    vol: 2,
    kind: "mockup",
    title: "Tarn / Treeline / Massif",
    src: "/studio/NM-0034_mockup_v2-plywood-trio.jpg",
    w: 1800,
    h: 900,
  },
  {
    n: 35,
    vol: 2,
    kind: "motion",
    title: "Treeline · Water",
    src: "/studio/NM-0035_motion_v2-treeline-water.mp4",
    poster: "/studio/NM-0035_motion_v2-treeline-water_poster.jpg",
    w: 1080,
    h: 1350,
  },
];
