export type Work = {
  n: number;
  vol: 1 | 2;
  kind: "poster" | "mark" | "pattern" | "mockup" | "motion";
  title: string;
  note?: string;
  src: string;
  poster?: string;
  w: number;
  h: number;
};

export const WORKS: Work[] = [
  {
    n: 1,
    vol: 1,
    kind: "poster",
    title: "Derez",
    note: "Ordered-dither landscape: fractal noise pushed through a Bayer matrix into five inks.",
    src: "/studio/NM-0001_poster_low-res-god.jpg",
    w: 960,
    h: 1200,
  },
  {
    n: 2,
    vol: 1,
    kind: "poster",
    title: "Slipstream",
    note: "Op-art stripes bent by a gaussian bulge and noise, counterchanged across three bands.",
    src: "/studio/NM-0002_poster_whorl.jpg",
    w: 960,
    h: 1200,
  },
  {
    n: 3,
    vol: 1,
    kind: "poster",
    title: "Bitstream",
    note: "A 40×50 glyph grid: noise picks the character, concentric rings pick the ink.",
    src: "/studio/NM-0003_poster_cipher.jpg",
    w: 960,
    h: 1200,
  },
  {
    n: 4,
    vol: 1,
    kind: "poster",
    title: "Flare",
    note: "Smeared thermal field: displaced noise mapped through a 7-stop heat ramp, screened as Benday dots.",
    src: "/studio/NM-0004_poster_sear.jpg",
    w: 960,
    h: 1200,
  },
  {
    n: 5,
    vol: 1,
    kind: "poster",
    title: "Overprint",
    note: "Eleven torn paper shapes overprinted in four riso inks with deliberate misregistration.",
    src: "/studio/NM-0005_poster_cut-up-misreg.jpg",
    w: 960,
    h: 1200,
  },
  {
    n: 6,
    vol: 1,
    kind: "poster",
    title: "Pulsar",
    note: "Radial burst: 26 rays XOR 9 wobbling rings, flipping palette past a radius.",
    src: "/studio/NM-0006_poster_dahlia.jpg",
    w: 960,
    h: 1200,
  },
  {
    n: 7,
    vol: 1,
    kind: "poster",
    title: "Quadrant",
    note: "Random 24×24 pixel seed mirrored four ways into a single emblem.",
    src: "/studio/NM-0007_poster_fold.jpg",
    w: 960,
    h: 1200,
  },
  {
    n: 8,
    vol: 1,
    kind: "poster",
    title: "Isoline 081",
    note: "Thirty-four isolines through a fractal heightfield, banded in four tints.",
    src: "/studio/NM-0008_poster_terrain-survey.jpg",
    w: 960,
    h: 1200,
  },
  {
    n: 9,
    vol: 1,
    kind: "poster",
    title: "Dropout",
    note: "Television snow with horizontal tears and chroma split, type cut out in magenta.",
    src: "/studio/NM-0009_poster_hiss.jpg",
    w: 960,
    h: 1200,
  },
  {
    n: 10,
    vol: 1,
    kind: "poster",
    title: "Lumen",
    note: "A halftone portrait of four light sources, screened at 22°.",
    src: "/studio/NM-0010_poster_stipple.jpg",
    w: 960,
    h: 1200,
  },
  {
    n: 11,
    vol: 1,
    kind: "mark",
    title: "Sixteen Marks",
    note: "Sixteen emblems from one rule-set of six primitives: sliced circle, stepped bars, quarter-quads, starburst, mirrored pixel glyph, cut target.",
    src: "/studio/NM-0011_mark_glyph-marks-16.jpg",
    w: 1200,
    h: 1200,
  },
  {
    n: 12,
    vol: 1,
    kind: "pattern",
    title: "Sawtooth",
    note: "Seamless zigzag repeat: 12 peaks × 20 bands, four inks. Tiles edge to edge.",
    src: "/studio/NM-0012_pattern_zig.jpg",
    w: 1200,
    h: 1200,
  },
  {
    n: 13,
    vol: 1,
    kind: "pattern",
    title: "Interlace",
    note: "Basket-weave repeat: alternating four-stripe ribbons, 12×12 tile.",
    src: "/studio/NM-0013_pattern_weave.jpg",
    w: 1200,
    h: 1200,
  },
  {
    n: 14,
    vol: 1,
    kind: "pattern",
    title: "XOR",
    note: "Checkerboard XOR circles: every dot inverts the square it sits in. 8×8 seamless tile.",
    src: "/studio/NM-0014_pattern_counterchange.jpg",
    w: 1200,
    h: 1200,
  },
  {
    n: 15,
    vol: 1,
    kind: "pattern",
    title: "Circuit",
    note: "Random slash and backslash maze in monospace: the classic 10 PRINT rule as wallpaper.",
    src: "/studio/NM-0015_pattern_ten-print.jpg",
    w: 1200,
    h: 1200,
  },
  {
    n: 16,
    vol: 1,
    kind: "pattern",
    title: "Dither Ramp",
    note: "Four-ink Bayer gradient swatch, the texture used across the poster series.",
    src: "/studio/NM-0016_pattern_dither-swatch.jpg",
    w: 1200,
    h: 1200,
  },
  {
    n: 17,
    vol: 1,
    kind: "mockup",
    title: "Fly-Poster Wall",
    note: "The ten posters wheat-pasted as a street run, lit from top-left.",
    src: "/studio/NM-0017_mockup_fly-poster-wall.jpg",
    w: 1800,
    h: 1125,
  },
  {
    n: 18,
    vol: 1,
    kind: "mockup",
    title: "Gallery Pair",
    note: "Flare and Pulsar framed as a giclée pair.",
    src: "/studio/NM-0018_mockup_gallery-pair.jpg",
    w: 1800,
    h: 1200,
  },
  {
    n: 19,
    vol: 1,
    kind: "mockup",
    title: "Quadrant — App",
    note: "Quadrant as a live-seed generator app: reroll the emblem, read its recipe.",
    src: "/studio/NM-0019_mockup_phone-fold-app.jpg",
    w: 1440,
    h: 1800,
  },
  {
    n: 20,
    vol: 1,
    kind: "mockup",
    title: "XOR Tote",
    note: "The XOR pattern as an all-over tote print.",
    src: "/studio/NM-0020_mockup_tote-counterchange.jpg",
    w: 1440,
    h: 1800,
  },
  {
    n: 22,
    vol: 1,
    kind: "mockup",
    title: "Signal & Noise Zine",
    note: "Bitstream and Overprint as a riso zine spread.",
    src: "/studio/NM-0022_mockup_zine-spread.jpg",
    w: 1800,
    h: 1238,
  },
  {
    n: 23,
    vol: 1,
    kind: "motion",
    title: "Slipstream — Loop",
    note: "Stripes flow through the bulge, 4-second seamless loop.",
    src: "/studio/NM-0023_motion_whorl-loop.mp4",
    poster: "/studio/NM-0023_motion_whorl-loop_poster.jpg",
    w: 1080,
    h: 1350,
  },
  {
    n: 24,
    vol: 1,
    kind: "motion",
    title: "Pulsar — Loop",
    note: "Rays rotate against pulsing rings, seamless loop.",
    src: "/studio/NM-0024_motion_dahlia-loop.mp4",
    poster: "/studio/NM-0024_motion_dahlia-loop_poster.jpg",
    w: 1080,
    h: 1350,
  },
  {
    n: 25,
    vol: 1,
    kind: "motion",
    title: "Derez — Tide",
    note: "A wave rolls through the Bayer-dithered field.",
    src: "/studio/NM-0025_motion_dither-tide.mp4",
    poster: "/studio/NM-0025_motion_dither-tide_poster.jpg",
    w: 1080,
    h: 1350,
  },
  {
    n: 26,
    vol: 1,
    kind: "motion",
    title: "Quadrant — Reroll",
    note: "The Quadrant generator rerolling six seeds a second.",
    src: "/studio/NM-0026_motion_fold-reroll.mp4",
    poster: "/studio/NM-0026_motion_fold-reroll_poster.jpg",
    w: 1080,
    h: 1350,
  },
  {
    n: 27,
    vol: 2,
    kind: "poster",
    title: "Horizon",
    src: "/studio/NM-0027_poster_v2-altitude.jpg",
    w: 960,
    h: 1200,
  },
  {
    n: 28,
    vol: 2,
    kind: "poster",
    title: "Tarn",
    src: "/studio/NM-0028_poster_v2-tarn.jpg",
    w: 960,
    h: 1200,
  },
  {
    n: 29,
    vol: 2,
    kind: "poster",
    title: "Headland",
    src: "/studio/NM-0029_poster_v2-headland.jpg",
    w: 960,
    h: 1200,
  },
  {
    n: 30,
    vol: 2,
    kind: "poster",
    title: "Treeline",
    src: "/studio/NM-0030_poster_v2-treeline.jpg",
    w: 960,
    h: 1200,
  },
  {
    n: 31,
    vol: 2,
    kind: "poster",
    title: "Massif",
    src: "/studio/NM-0031_poster_v2-massif.jpg",
    w: 960,
    h: 1200,
  },
  {
    n: 32,
    vol: 2,
    kind: "poster",
    title: "Estuary",
    src: "/studio/NM-0032_poster_v2-estuary.jpg",
    w: 960,
    h: 1200,
  },
  {
    n: 33,
    vol: 2,
    kind: "mockup",
    title: "Horizon — Plywood Wall",
    note: "Horizon hung on a plywood wall in low window light.",
    src: "/studio/NM-0033_mockup_v2-plywood-altitude.jpg",
    w: 1800,
    h: 1013,
  },
  {
    n: 34,
    vol: 2,
    kind: "mockup",
    title: "Tarn / Treeline / Massif",
    note: "Three Volume 02 prints hung as a triptych.",
    src: "/studio/NM-0034_mockup_v2-plywood-trio.jpg",
    w: 1800,
    h: 900,
  },
  {
    n: 35,
    vol: 2,
    kind: "motion",
    title: "Treeline — Water",
    note: "The lake moving: ripples and glint lines cycle through the reflection, dithered live.",
    src: "/studio/NM-0035_motion_v2-treeline-water.mp4",
    poster: "/studio/NM-0035_motion_v2-treeline-water_poster.jpg",
    w: 1080,
    h: 1350,
  },
];
