"use client";

// MarginAnnotation — craft notes in the right gutter.
//
// When Flow mode is on, Book Mind periodically analyzes the current
// chapter and drops short craft annotations. Not grammar (Grammarly
// territory) — craft: dialogue-tag overload, repeated openings,
// character drift, pacing observations. Each note is one sentence max
// and links to the line it references.
//
// Annotations are generated by a debounced Haiku call every 30 seconds
// of editing or 200 words of new content (whichever comes first). The
// results are stored in component state (not persisted to localStorage)
// so they reset when the user changes chapters or closes Flow mode.
//
// This component owns the timer, the API call, and the rendering.
// It's positioned in the right margin of the editor canvas.

import React, { useState, useEffect, useRef, useCallback } from "react";
import { useBookMind } from "../../hooks/useBookMind";

export interface Annotation {
  id: string;
  note: string;
  type: "craft" | "pacing" | "voice" | "repetition";
}

interface MarginAnnotationProps {
  enabled: boolean;
  bookId?: string;
  userId?: string;
  chapterContent: string;
  chapterTitle: string;
}

const DEBOUNCE_MS = 30_000; // 30 seconds after last edit
const MIN_WORDS_DELTA = 200; // or after 200 new words

export default function MarginAnnotation({
  enabled,
  bookId,
  userId,
  chapterContent,
  chapterTitle,
}: MarginAnnotationProps) {
  const { inlineEdit } = useBookMind({ bookId, userId });

  const [annotations, setAnnotations] = useState<Annotation[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [dismissed, setDismissed] = useState<Set<string>>(new Set());

  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const lastWordCountRef = useRef(0);
  const lastContentRef = useRef("");

  // Count words (simple split)
  const wordCount = chapterContent.trim().split(/\s+/).filter(Boolean).length;

  // Reset annotations when chapter changes or flow mode toggles
  useEffect(() => {
    setAnnotations([]);
    setDismissed(new Set());
    lastWordCountRef.current = wordCount;
    lastContentRef.current = chapterContent;
  }, [chapterTitle, enabled]);

  // Debounced annotation generation
  useEffect(() => {
    if (!enabled || !chapterContent.trim()) return;

    const wordsDelta = wordCount - lastWordCountRef.current;
    const contentChanged = chapterContent !== lastContentRef.current;

    if (!contentChanged) return;
    lastContentRef.current = chapterContent;

    // Clear existing timer
    if (timerRef.current) clearTimeout(timerRef.current);

    // If enough new words, generate sooner (5s instead of 30s)
    const delay = wordsDelta >= MIN_WORDS_DELTA ? 5000 : DEBOUNCE_MS;

    timerRef.current = setTimeout(async () => {
      if (!enabled) return;
      lastWordCountRef.current = wordCount;
      setIsGenerating(true);

      try {
        const result = await inlineEdit({
          selectedText: chapterContent.slice(-3000), // last ~3000 chars for context
          instruction: `You are a craft reader. Read this chapter excerpt and return 2-4 brief craft annotations as a JSON array. Each annotation is one object: {"id":"<unique>","note":"<one sentence, max 15 words>","type":"craft"|"pacing"|"voice"|"repetition"}.

Focus on CRAFT only:
- Repeated sentence openings in recent paragraphs
- Dialogue tags doing too much work ("he said angrily" vs action beats)
- Pacing: a paragraph that's notably longer/shorter than its neighbors
- A character using a speech pattern that belongs to a different character

Do NOT flag grammar, spelling, or punctuation. Return ONLY the JSON array, no prose. If nothing notable, return [].`,
        });

        if (result) {
          try {
            const parsed = JSON.parse(result.trim());
            if (Array.isArray(parsed)) {
              setAnnotations(parsed.filter(
                (a: unknown): a is Annotation =>
                  typeof a === "object" && a !== null &&
                  typeof (a as Annotation).note === "string" &&
                  typeof (a as Annotation).id === "string",
              ));
            }
          } catch {
            // Model returned non-JSON — silently skip
          }
        }
      } catch {
        // Silently ignore — annotations are best-effort
      } finally {
        setIsGenerating(false);
      }
    }, delay);

    return () => {
      if (timerRef.current) clearTimeout(timerRef.current);
    };
  }, [enabled, chapterContent, wordCount, inlineEdit]);

  const handleDismiss = (id: string) => {
    setDismissed(prev => new Set(prev).add(id));
  };

  const visible = annotations.filter(a => !dismissed.has(a.id));

  if (!enabled || (visible.length === 0 && !isGenerating)) return null;

  const TYPE_COLORS: Record<Annotation["type"], string> = {
    craft: "text-[#4070ff] bg-[#4070ff]/10",
    pacing: "text-purple-600 bg-purple-500/10 dark:text-purple-400",
    voice: "text-emerald-600 bg-emerald-500/10 dark:text-emerald-400",
    repetition: "text-amber-600 bg-amber-500/10 dark:text-amber-400",
  };

  return (
    <div className="absolute top-0 right-0 w-48 pt-16 pr-2 space-y-2 pointer-events-auto">
      {isGenerating && visible.length === 0 && (
        <div className="flex items-center gap-1.5 px-2 py-1 text-2xs text-gray-400 dark:text-[#737373]">
          <svg className="w-3 h-3 animate-spin" fill="none" viewBox="0 0 24 24">
            <circle cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="3" strokeOpacity="0.2" />
            <path d="M22 12a10 10 0 0 1-10 10" stroke="currentColor" strokeWidth="3" strokeLinecap="round" />
          </svg>
          Reading...
        </div>
      )}
      {visible.map(annotation => (
        <div
          key={annotation.id}
          className="group flex items-start gap-1.5 px-2 py-1.5 rounded-lg bg-white/80 dark:bg-[#1e1e1e]/80 backdrop-blur-sm border border-gray-100 dark:border-[#2f2f2f] shadow-sm"
        >
          <span className={`text-[9px] font-semibold uppercase tracking-wide px-1 py-0.5 rounded flex-shrink-0 mt-0.5 ${TYPE_COLORS[annotation.type] || TYPE_COLORS.craft}`}>
            {annotation.type}
          </span>
          <p className="text-[11px] text-gray-600 dark:text-[#a3a3a3] leading-snug flex-1">
            {annotation.note}
          </p>
          <button
            onClick={() => handleDismiss(annotation.id)}
            className="flex-shrink-0 opacity-0 group-hover:opacity-100 text-gray-400 hover:text-gray-700 dark:hover:text-white transition-all mt-0.5"
            title="Dismiss"
          >
            <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
      ))}
    </div>
  );
}
